### ISSUE TITLE
ERROR: Service 'spacewalk' failed to build: The command '/bin/sh -c rpm -Uvh http://yum.spacewalkproject.org/2.7/Fedora/26/x86_64/spacewalk-repo-2.7-2.fc26.noarch.rpm

### ISSUE THREAD

**Issue by kamal2222ahmed** [Zerrtech/spacewalk#1]
got the following error when trying to run docker-compose up

Step 7/29 : RUN rpm -Uvh http://yum.spacewalkproject.org/2.7/Fedora/26/x86_64/spacewalk-repo-2.7-2.fc26.noarch.rpm &&   rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&   (cd /etc/yum.repos.d && curl -O https://copr.fedorainfracloud.org/coprs/g/spacewalkproject/java-packages/repo/epel-7/group_spacewalkproject-java-packages-epel-7.repo) &&    yum -y install spacewalk-postgresql initscripts sqlite supervisor && yum clean all
 ---> Running in 1b2a1e331060
warning: /var/tmp/rpm-tmp.Bq0JNd: Header V4 DSA/SHA1 Signature, key ID b8002de1: NOKEY
Retrieving http://yum.spacewalkproject.org/2.7/Fedora/26/x86_64/spacewalk-repo-2.7-2.fc26.noarch.rpm
Preparing...                          ########################################
Updating / installing...
spacewalk-repo-2.7-2.fc26             ########################################
warning: /var/tmp/rpm-tmp.ZgfYKA: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
error: Failed dependencies:
        fedora-release conflicts with epel-release-7-11.noarch
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
ERROR: Service 'spacewalk' failed to build: The command '/bin/sh -c rpm -Uvh http://yum.spacewalkproject.org/2.7/Fedora/26/x86_64/spacewalk-repo-2.7-2.fc26.noarch.rpm &&    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&      (cd /etc/yum.repos.d && curl -O https://copr.fedorainfracloud.org/coprs/g/spacewalkproject/java-packages/repo/epel-7/group_spacewalkproject-java-packages-epel-7.repo) &&         yum -y install spacewalk-postgresql initscripts sqlite supervisor && yum clean all' returned a non-zero code: 1

I tried with specifying PROXY in the Dockerfile, same results

**Comment by kamal2222ahmed** [comment]
i am on RHEL 7.4
docker-compose version 1.16.1, build 6d1ac21 
Docker version 17.11.0-ce, build 1caf76c

**Comment by israelshirk** [comment]
Don’t think this ever made it to production; it’s still in my backlog somewhere.  Sorry I can’t help more.
